#! /bin/sh

sxhkd &
compton -b
$HOME/.config/polybar/launch.sh &
$HOME/Pictures/Background/auto-change.sh &
fcitx &
redshift-gtk &
xdman &
xautolock -time 10 -locker '/usr/bin/lock' -corners ---- -cornersize 30 &
xsetroot -cursor_name left_ptr
wmname LG3D
caffeine &
xfce4-power-manager &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#ff79c6"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a java-lang-Thread desktop='^8' state=floating
bspc rule -a xdman-Main state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a netease-cloud-music desktop='^4' state=floating
bspc rule -a deepin-system-monitor state=floating
bspc rule -a 'VirtualBox Manager' desktop='^6' state=floating
bspc rule -a 'VirtualBox Machine' desktop='^6' 
bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating
bspc rule -a Code desktop='^2'
bspc rule -a jetbrains-idea desktop='^2'
bspc rule -a jetbrains-pycharm desktop='^2'
bspc rule -a jetbrains-clion desktop='^2'
bspc rule -a jetbrains-webstorm desktop='^2'
bspc rule -a jetbrains-datagrip desktop='^2'

