#! /bin/sh
sh $HOME/.config/bspwm/scripts/autostart.sh

bspc monitor -d J u s t D o I t

bspc config border_width         3
bspc config window_gap           10
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle      true
unclutter --ignore-scrooling &

bspc rule -a firefox desktop='^3'
bspc rule -a Nightly desktop='^3' state=tiled
bspc rule -a FirefoxNightly desktop='^3' state=tiled
bspc rule -a xdman-Main state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Lxappearance state=floating
bspc rule -a Xfce4-about state=floating
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a kitty-music desktop='^4' state=pseudo_tiled
bspc rule -a spotify desktop='^4' state=pseudo_tiled
bspc rule -a 'VirtualBox Manager' desktop='^6' state=floating
bspc rule -a 'VirtualBox Machine' desktop='^6'
bspc rule -a "Qalculate-gtk" state=floating
bspc rule -a Qq state=floating desktop='^8'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a Gpick state=floating
bspc rule -a jetbrains-toolbox state=floating
bspc rule -a jetbrains-idea desktop='^2'
bspc rule -a jetbrains-pycharm desktop='^2'
bspc rule -a jetbrains-clion desktop='^2'
bspc rule -a jetbrains-webstorm desktop='^2'
bspc rule -a jetbrains-datagrip desktop='^2'
bspc rule -a jetbrains-phpstorm desktop='^2'
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a jetbrains-goland desktop='^2'
